//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 07:40:02 PM MSK 
//


package com.main.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="doctors" type="{urn:ns}doctors" minOccurs="0"/&gt;
 *         &lt;element name="specialties" type="{urn:ns}specialties" minOccurs="0"/&gt;
 *         &lt;element name="services" type="{urn:ns}services" minOccurs="0"/&gt;
 *         &lt;element name="patients" type="{urn:ns}patients" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "root")
public class RootXml {

    protected DoctorsXml doctors;
    protected SpecialtiesXml specialties;
    protected ServicesXml services;
    protected PatientsXml patients;

    /**
     * Gets the value of the doctors property.
     * 
     * @return
     *     possible object is
     *     {@link DoctorsXml }
     *     
     */
    public DoctorsXml getDoctors() {
        return doctors;
    }

    /**
     * Sets the value of the doctors property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoctorsXml }
     *     
     */
    public void setDoctors(DoctorsXml value) {
        this.doctors = value;
    }

    /**
     * Gets the value of the specialties property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialtiesXml }
     *     
     */
    public SpecialtiesXml getSpecialties() {
        return specialties;
    }

    /**
     * Sets the value of the specialties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialtiesXml }
     *     
     */
    public void setSpecialties(SpecialtiesXml value) {
        this.specialties = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesXml }
     *     
     */
    public ServicesXml getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesXml }
     *     
     */
    public void setServices(ServicesXml value) {
        this.services = value;
    }

    /**
     * Gets the value of the patients property.
     * 
     * @return
     *     possible object is
     *     {@link PatientsXml }
     *     
     */
    public PatientsXml getPatients() {
        return patients;
    }

    /**
     * Sets the value of the patients property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientsXml }
     *     
     */
    public void setPatients(PatientsXml value) {
        this.patients = value;
    }

}
