//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 07:40:02 PM MSK 
//


package com.main.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for doctor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="doctor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:ns}person"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="category" type="{urn:ns}category"/&gt;
 *         &lt;element name="experience" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/&gt;
 *         &lt;element name="vacation_start" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="vacation_end" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="specialty_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="services_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREFS" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "doctor", propOrder = {
    "category",
    "experience",
    "vacationStart",
    "vacationEnd"
})
public class DoctorXml
    extends PersonXml
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CategoryXml category;
    @XmlSchemaType(name = "unsignedShort")
    protected int experience;
    @XmlElement(name = "vacation_start", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar vacationStart;
    @XmlElement(name = "vacation_end", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar vacationEnd;
    @XmlAttribute(name = "specialty_ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object specialtyRef;
    @XmlAttribute(name = "services_ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> servicesRef;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryXml }
     *     
     */
    public CategoryXml getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryXml }
     *     
     */
    public void setCategory(CategoryXml value) {
        this.category = value;
    }

    /**
     * Gets the value of the experience property.
     * 
     */
    public int getExperience() {
        return experience;
    }

    /**
     * Sets the value of the experience property.
     * 
     */
    public void setExperience(int value) {
        this.experience = value;
    }

    /**
     * Gets the value of the vacationStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVacationStart() {
        return vacationStart;
    }

    /**
     * Sets the value of the vacationStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVacationStart(XMLGregorianCalendar value) {
        this.vacationStart = value;
    }

    /**
     * Gets the value of the vacationEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVacationEnd() {
        return vacationEnd;
    }

    /**
     * Sets the value of the vacationEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVacationEnd(XMLGregorianCalendar value) {
        this.vacationEnd = value;
    }

    /**
     * Gets the value of the specialtyRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSpecialtyRef() {
        return specialtyRef;
    }

    /**
     * Sets the value of the specialtyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSpecialtyRef(Object value) {
        this.specialtyRef = value;
    }

    /**
     * Gets the value of the servicesRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the servicesRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServicesRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getServicesRef() {
        if (servicesRef == null) {
            servicesRef = new ArrayList<Object>();
        }
        return this.servicesRef;
    }

}
