//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 07:40:02 PM MSK 
//


package com.main.model.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ns package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ns
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RootXml }
     * 
     */
    public RootXml createRoot() {
        return new RootXml();
    }

    /**
     * Create an instance of {@link DoctorsXml }
     * 
     */
    public DoctorsXml createDoctors() {
        return new DoctorsXml();
    }

    /**
     * Create an instance of {@link SpecialtiesXml }
     * 
     */
    public SpecialtiesXml createSpecialties() {
        return new SpecialtiesXml();
    }

    /**
     * Create an instance of {@link ServicesXml }
     * 
     */
    public ServicesXml createServices() {
        return new ServicesXml();
    }

    /**
     * Create an instance of {@link PatientsXml }
     * 
     */
    public PatientsXml createPatients() {
        return new PatientsXml();
    }

    /**
     * Create an instance of {@link SpecialtyXml }
     * 
     */
    public SpecialtyXml createSpecialty() {
        return new SpecialtyXml();
    }

    /**
     * Create an instance of {@link ServiceXml }
     * 
     */
    public ServiceXml createService() {
        return new ServiceXml();
    }

    /**
     * Create an instance of {@link PatientXml }
     * 
     */
    public PatientXml createPatient() {
        return new PatientXml();
    }

    /**
     * Create an instance of {@link DoctorXml }
     * 
     */
    public DoctorXml createDoctor() {
        return new DoctorXml();
    }

}
