//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 07:40:02 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ns", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.main.model.xml;
